### ISSUE TITLE
tx produces more unlocked (1000000) than it consumes (0)

### ISSUE THREAD

**Issue by kmlcgn** [ava-labs/avalanche-docs#1048] opened 2022-10-19 22:05 UTC
I am following the official guide named “[Deploying Subnet with EVM Based Blockchain using AvalancheJS](https://docs.avax.network/subnets/create-a-evm-blockchain-on-subnet-with-avalanchejs)”

- I am using the same genesis.json file with updated data as indicated in the guide.
- The problem occurs at the step in which we add a validator to our subnet. We simply try to run the file named addSubnetValidator.js.

The screenshot of the error message: 
<img width="570" alt="Ekran Resmi 2022-10-20 01 04 10" src="https://user-images.githubusercontent.com/47904355/196813335-97449866-b766-43a2-a208-ba31eba0d48c.png">

The error message:
```
/Users/usr/node_modules/avalanche/dist/common/jrpcapi.js:64
                    throw new Error(resp.data.error.message);
                          ^

Error: couldn't issue tx: flow check failed: tx produces more unlocked "BUuypiq2wyuLMvyhzFXcPyxPMCgSp7eeDohhQRqTChoBjKziC" (1000000) than it consumes (0)
```

**Comment by yulin-dong** [comment] 2022-10-19 22:20
Please provide detail on which tutorial you were following.

**Comment by kmlcgn** [comment] 2022-10-19 22:23
I followed this documentation: https://docs.avax.network/subnets/create-a-evm-blockchain-on-subnet-with-avalanchejs
Which is also the same as this repository’s readme file.

**Comment by kmlcgn** [comment] 2022-10-20 11:47
> Please provide detail on which tutorial you were following.

Hi Yulin, any updates?

**Comment by rajranjan0608** [comment] 2022-10-21 08:36
Hi @kmlcgn. We are looking into it. Will keep you posted. Thanks.

**Comment by canatakan** [comment] 2022-10-25 20:20
Hello @rajranjan0608, are there any updates on this? I am also having this issue. There seems to be something wrong with the guide mentioned above or the AvalancheJS library itself.

**Comment by rajranjan0608** [comment] 2022-10-26 03:08
Hi @kmlcgn and @canatakan. I can confirm there's a bug in AvalancheJS. This PR will resolve the issue: https://github.com/ava-labs/avalanchejs/pull/664

**Comment by kmlcgn** [comment] 2022-10-26 13:18
Hi @rajranjan0608, thank you!

**Comment by rajranjan0608** [comment] 2022-10-28 05:34
The issue has been fixed now with the latest AvalancheJS release. Please update your AvalancheJS version to use [v3.15.5](https://github.com/ava-labs/avalanchejs/releases/tag/v3.15.5). Thanks for raising this issue 👍

**Closed** 2022-10-28 08:43 UTC
